# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 03:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[a-zA-Z\xf1\xd1\xfc\xdc\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda'\\s\\.]*$", 'S\xf3lo se permiten caracteres al fab\xe9ticos')], verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[a-zA-Z\xf1\xd1\xfc\xdc\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda'\\s\\.]*$", 'S\xf3lo se permiten caracteres al fab\xe9ticos')], verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('DN', 'Documento \xfanico'), ('LC', 'Libreta c\xedvica'), ('LE', 'Libreta enrolamiento'), ('PA', 'Pasaporte'), ('UN', 'No definido')], default='DN', max_length=2, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('\\d\\d\\d\\d\\d\\d\\d\\d', 'El nro debe constar de ocho d\xedgitos sin espacios o puntos')], verbose_name='Nro. de Documento')),
                ('cuil', models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator('\\d\\d\\d\\d\\d\\d\\d\\d', 'El nro debe constar de once d\xedgitos sin espacios o puntos')], verbose_name='Cuil')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
            ],
            options={
                'ordering': ['last_names'],
                'verbose_name': 'Persona',
                'verbose_name_plural': 'People',
            },
        ),
    ]
