# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, verbose_name='Rol')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Descripci\xf3n')),
            ],
            options={
                'ordering': ['role_name'],
                'verbose_name': 'Rol',
            },
        ),
    ]
